entity = class:new()

entitylist = {	
	"remove",
	"mushroom",
	"oneup",
	"star",
	"manycoins",
	"goomba",
	"koopa",
	"spawn",
	"goombahalf",
	"koopahalf",
	"flag",
	"koopared",
	"kooparedhalf",
	"vine",
	"hammerbro",
	"cheepred",
	"cheepwhite",
	"platformup", --my mouse is dying :(
	"platformright",
	"box",
	"pipe",
	"lakito",
	"mazestart",
	"mazeend",
	"mazegate",
	"emancehor",
	"emancever",
	"doorver",
	"doorhor",
	"wallindicator",
	"pipespawn",
	"platformfall",
	"bulletbillstart",
	"bulletbillend",
	"drain",
	"lightbridgeright",
	"lightbridgeleft",
	"lightbridgedown",
	"lightbridgeup",
	"button",
	"platformspawnerdown",
	"platformspawnerup",
	"groundlightver",
	"groundlighthor",
	"groundlightupright",
	"groundlightrightdown",
	"groundlightdownleft",
	"groundlightleftup",
	"faithplateup",
	"faithplateright",
	"faithplateleft",
	"laserright",
	"laserdown",
	"laserleft",
	"laserup",
	"laserdetectorright",
	"laserdetectordown",
	"laserdetectorleft",
	"laserdetectorup",
	"bulletbill",
	"bluegeldown",
	"bluegelright",
	"bluegelleft",
	"orangegeldown",
	"orangegelright",
	"orangegelleft",
	"boxtube",
	"pushbuttonleft",
	"pushbuttonright",
	"plant",
	"whitegeldown",
	"whitegelright",
	"whitegelleft",
	"timer",
	"beetle",
	"beetlehalf",
	"kooparedflying",
	"koopaflying",
	"castlefireccw",
	"seesaw",
	"warppipe",
	"castlefirecw",
	"lakitoend",
	"notgate",
	"geltop",
	"gelleft",
	"gelbottom",
	"gelright",
	"firestart",
	"bowser",
	"axe",
	"platformbonus",
	"spring",
	"squid",
	"flyingfishstart",
	"flyingfishend",
	"upfire",
	"spikey",
	"spikeyhalf",
	"checkpoint",
	"poisonmush",
	"downplant",
	"paragoomba",
	"bigbill",
	"kingbill",
	"sidestepper",
	"barrel",
	"icicle",
	"angrysun",
	"angrysunend",
	"splunkin",
	"splunkinhalf",
	"threeup",
	"biggoomba",
	"bigspikey",
	"bigkoopa",
	"shell",
	"goombrat",
	"goombrathalf",
	"firebro",--yeah I know turtle already made them :(
	"plusclock",
	"springgreen",
	"redplant",
	"reddownplant",
	"thwomp",
	"fishbone",
	"drybones",
	"dryboneshalf",
	"muncher",
	"bigbeetle",
	"meteorstart",
	"meteorend",
	"drygoomba",
	"drygoombahalf",
	"dryplant",
	"drydownplant",
	"donut",
	"boomerangbro",
	"parabeetle",
	"ninji",
	"hammersuit",
	"boo",
	"mole",
	"bigmole",
	"bomb",
	"bombhalf",
	"fireplant",
	"flipblock",
	"downfireplant",
	"torpedoted",
	"frogsuit",
	"parabeetleright",
	"boomboom",
	"levelball",
	"leaf",
	"koopablue",
	"koopabluehalf",
	"koopaflying2",
	"windstart",
	"windend",
	"pipe2",
	"pinksquid",
	"door", --not portal
	"ice",
	"box2",
	"energylauncherright",
	"energylauncherleft",
	"energylauncherup",
	"energylauncherdown",
	"energycatcherright",
	"energycatcherleft",
	"energycatcherup",
	"energycatcherdown",
	"turretleft",
	"turretright",
	"turret2left",
	"turret2right",
	"blocktogglebutton",
	"buttonblockon",
	"buttonblockoff",
	"purplegeldown",
	"purplegelright",
	"purplegelleft",
	"sleepfish",
	"squarewave",
	"delayer",
	"coin",
	"amp",
	"parabeetlegreen",
	"parabeetlegreenright",
	"longfire",
	"cannonball",
	"minimushroom",
	"rocketturret",
	"glados",
	"pedestal",
	"portal1",
	"portal2",
	"text",
	"regiontrigger",
	"tiletool",
	"iceflower",
	"shyguy",
	"shyguyhalf",
	"enemytool",
	"randomizer",
	"yoshi",
	"bigblocktogglebutton",
	"beetleshell",
	"musicchanger"
}

entitydescriptions = {
	"place anywhere - acts as an entity eraser", --"remove",
	"place on a wall - mushroom", --"mushroom",
	"place on a wall - 1-up", --"oneup",
	"place on a wall - star", --"star",
	"place on a non question mark block - gives several coins", --"manycoins",
	"place on empty tile - goomba", --"goomba",
	"place on empty tile - koopa", --"koopa",
	"place on empty tile - mario's starting point", --"spawn",
	"place on empty tile - goomba - more to the right", --"goombahalf",
	"place on empty tile - koopa - more to the right", --"koopahalf",
	"place on a wall - bottom of the flag } end of level", --"flag",
	"place on empty tile - red koopa - will turn around at an edge", --"koopared",
	"place on empty tile - red koopa - more to the right", --"kooparedhalf",
	"place on wall - vine - right click to choose destination", --"vine",
	"place on empty tile - hammer bro", --"hammerbro",
	"place on empty underwater tile - cheep cheep fish - red", --"cheepred",
	"place on empty underwater tile - cheep cheep fish - white", --"cheepwhite",
	"place on empty tile - oscillating platform - right click for width", --"platformup", --my mouse is dying :(
	"place on empty tile - oscillating platform - right click for width", --"platformright",
	"place on empty tile - weighted storage cube", --"box",
	"place on pipe tile - pipe - right click for destination sublevel", --"pipe",
	"place on empty tile - lakito - you can also add a lakito end tile", --"lakito",
	"place on empty tile - logical maze start", --"mazestart",
	"place on empty tile - logical maze end", --"mazeend",
	"place on empty tile - maze gate - right click for the gate number", --"mazegate",
	"place on empty tile - horizontal emancipate grill - stops portals and companion cubes", --"emancehor",
	"place on empty tile - vertical emancipate grill - stops portals and companion cubes", --"emancever",
	"place on empty tile - vertical door - use link tool", --"doorver",
	"place on empty tile - horizontal door - use link tool", --"doorhor",
	"place on a wall - use link tool to show on or off state", --"wallindicator",
	"place on a pipe tile - right click for origin sublevel", --"pipespawn",
	"place on empty tile - falling platforms - right click for width", --"platformfall",
	"place anywhere - beginning of bullet zone", --"bulletbillstart",
	"place anywhere - end of bullet zone", --"bulletbillend",
	"place at the very bottom in an underwater level - drain - attracts mario down", --"drain",
	"place on empty tile - light bridge to right", --"lightbridgeright",
	"place on empty tile - light bridge to left", --"lightbridgeleft",
	"place on empty tile - light bridge to down", --"lightbridgedown",
	"place on empty tile - light bridge to up", --"lightbridgeup",
	"place on empty tile - floor button - use link", --"button",
	"place on top - down platform spawner - right click for width", --"platformspawnerdown",
	"place at the bottom - up platform spawner - right click for width", --"platformspawnerup",
	"place on wall - use link to show on/off state", --"groundlightver",
	"place on wall - use link to show on/off state", --"groundlighthor",
	"place on wall - use link to show on/off state", --"groundlightupright",
	"place on wall - use link to show on/off state", --"groundlightrightdown",
	"place on wall - use link to show on/off state", --"groundlightdownleft",
	"place on wall - use link to show on/off state", --"groundlightleftup",
	"place on ground wall - faith plate to the sky", --"faithplateup",
	"place on ground wall - faith plate to the right", --"faithplateright",
	"place on ground wall - faith plate to the left", --"faithplateleft",
	"place on empty tile - laser to right", --"laserright",
	"place on empty tile - laser to bottom", --"laserdown",
	"place on empty tile - laser to left", --"laserleft",
	"place on empty tile - laser to up", --"laserup",
	"place on right edge wall or empty tile - will send off signal if laser is detected - use link tool", --"laserdetectorright",
	"place on down edge wall or empty tile - will send off signal if laser is detected - use link tool", --"laserdetectordown",
	"place on left edge wall or empty tile - will send off signal if laser is detected - use link tool", --"laserdetectorleft",
	"place on up edge wall or empty tile - will send off signal if laser is detected - use link tool", --"laserdetectorup",
	"place on bulletbill launchers - will make the launcher actually launch bulletbills", --"bulletbill",
	"place on empty tile - will produce blue gel to down - blue gel } jump", --"bluegeldown",
	"place on empty tile - will produce blue gel to right - blue gel } jump", --"bluegelright",
	"place on empty tile - will produce blue gel to left - blue gel } jump", --"bluegelleft",
	"place on empty tile - will produce orange gel to down - orange gel } run", --"orangegeldown",
	"place on empty tile - will produce orange gel to right - orange gel } run", --"orangegelright",
	"place on empty tile - will produce orange gel to left - orange gel } run", --"orangegelleft",
	"place on empty tile - will drop a box and remove previous one - use link tool", --"boxtube",
	"place on empty tile - will send a single on signal when used - use link tool", --"pushbuttonleft",
	"place on empty tile - will send a single on signal when used - use link tool", --"pushbuttonright",
	"place on empty tile - piranha plant will go up and down", --"plant",
	"place on empty tile - will produce white gel to down - white gel } portalable", --"whitegeldown",
	"place on empty tile - will produce white gel to right - white gel } portalable", --"whitegelright",
	"place on empty tile - will produce white gel to left - white gel } portalable", --"whitegelleft",
	"place anywhere - will send on signal for a duration - right click to set duration", --"timer",
	"place on empty tile - beetle - runs fast and resists fireballs", --"beetle",
	"place on empty tile - beetle - more to the right", --"beetlehalf",
	"place on empty tile - red flying koopa, goes up and down", --"kooparedflying",
	"place on empty tile - green flying koopa, jumps around", --"koopaflying",
	"place on wall - counterclockwise rotating fire - right click for length", --"castlefireccw",
	"place on empty tile - see-saw - right click for see-saw type", --"seesaw",
	"place on wall - warp pipe - right click for destination world", --"warppipe",
	"place on wall - clockwise rotating fire - right click for width", --"castlefirecw",
	"place anywhere - defines a right border for lakito - use with lakito", --"lakitoend",
	"place anywhere - turns in input around", --notgate
	"place on tile - creates gel on this block. 1: blue, 2: orange, 3: white, 4:purple",
	"place on tile - creates gel on this block. 1: blue, 2: orange, 3: white, 4:purple",
	"place on tile - creates gel on this block. 1: blue, 2: orange, 3: white, 4:purple",
	"place on tile - creates gel on this block. 1: blue, 2: orange, 3: white, 4:purple",
	"place anywhere - fire start - bowser firethings will regularly cross the screen", --"firestart",
	"place on empty tile preferably on the first block on a bridge with an axe - bowser", --"bowser",
	"place on empty tile preferably behind a bridge - axe } end of level", --"axe",
	"place on empty tile - platform in coin worlds", --"platformbonus",
	"place on empty tile - spring", --"spring",
	"place on empty tile preferably underwater - squid", --"squid",
	"place anywhere - defines the start of a flying cheep cheep zone", --"flyingfishstart",
	"place anywhere - defines the end of a flying cheep cheep zone", --"flyingfishend",
	"place anywhere - a lava ball will jump up and down on this line", --"upfire",
	"place on empty tile - spikey", --"spikey",
	"place on empty tile - spikey - more to the right", --"spikeyhalf",
	"place on empty tile - checkpoint - mario will spawn there if he dies after reaching it", --"checkpoint",
	"place on a wall - poison mushroom", --"poisonmush",
	"place on empty tile - upside down piranha plant", --"downplant",
	"place on empty tile - paragoomba", --"paragoomba",
	"place on bulletbill launchers - will make the launcher actually launch banzaibills", --"bigbill",
	"place on empty tile - launches one giant king    bill - right click for speed", --"kingbill",
	"place on empty tile - side stepper", --"sidestepper",
	"place on empty tile - barrel", --"barrel",
	"place on empty tile - icicle - right click for   gravity", --"icicle",
	"place on empty tile - angry sun", --"angrysun",
	"place anywhere - defines a right border for angry sun - use with an angry sun", --"angrysunend",
	"place on empty tile - splunkin", --"splunkin",
	"place on empty tile - splunkin - more to the right", --"splunkinhalf",
	"place on a wall - 3-up moon", --"threeup",
	"place on empty tile - giant goomba", --"biggoomba",
	"place on empty tile - giant spikey", --"bigspikey",
	"place on empty tile - giant koopa", --"bigkoopa",
	"place on empty tile - koopa shell", --"shell",
	"place on empty tile - goombrat", --"goombrat",
	"place on empty tile - goombrat - more to the right", --"goombrathalf",
	"place on empty tile - fire bro", --"firebro"
	"place on a wall - clock", --"plusclock"
	"place on empty tile - green spring", --"springgreen"
	"place on empty tile - red piranha plant will go up and down fast", --"redplant",
	"place on empty tile - upside down red piranha plant", --"reddownplant",
	"place on empty tile - thwomp", --"thwomp",
	"place on empty underwater tile - fishbones - resists fireballs", --"fishbone",
	"place on empty tile - drybones - resists fireballs", --"drybones",
	"place on empty tile - drybones - more to the right", --"dryboneshalf",
	"place on empty tile - muncher", --"muncher",
	"place on empty tile - giant beetle", --"bigbeetle",
	"place anywhere - defines the start of a meteor zone", --"meteorstart",
	"place anywhere - defines the end of a meteor zone", --"meteorend",
	"place on empty tile - bone goomba - resists fireballs", --"drygoomba",
	"place on empty tile - bone goomba - more to the right", --"drygoombahalf",
	"place on empty tile - dry piranha plant - resists fireballs", --"dryplant",
	"place on empty tile - upside down dry piranha plant", --"drydownplant",
	"place on empty tile - donut platform - falls when stepped on", --"donut",
	"place on empty tile - boomerang bro", --"boomerangbro",
	"place anywhere - parabeetle - left", --"parabeetle",
	"place on empty tile - ninji", --"ninji",
	"place on a wall - hammer suit", --"hammersuit",
	"place anywhere - boo", --"boo",
	"place on empty tile - monty mole", --"mole",
	"place on empty tile - mega mole", --"bigmole",
	"place on empty tile - bob-omb", --"bomb",
	"place on empty tile - bob-omb - more to the right", --"bombhalf",
	"place on empty tile - venus firetrap - shoots fire", --"fireplant",
	"place on empty tile - rotating block - rotates when hit", --"donut",
	"place on empty tile - upside down venus firetrap", --"downfireplant",
	"place on empty tile - hand launches torpedo teds", --"torpedoted",
	"place on a wall - frog suit", --"frogsuit",
	"place anywhere - parabeetle - right", --"parabeetleright",
	"place on empty tile - boomboom", --"boomboom",
	"place on empty tile - ? ball - end of level",
	"place on a wall - raccoon leaf", --"leaf",
	"place on empty tile - blue koopa - moves fast", --"koopablue",
	"place on empty tile - blue koopa - more to the right", --"koopabluehalf",
	"place on empty tile - flying koopa, goes right and left", --"koopaflying2",
	"place anywhere - beginning of wind", --"windstart",
	"place anywhere - end of wind", --"windend",
	"place on pipe tile - pipe - right click for destination sublevel - enter left or up", --"pipe2?",
	"place on empty tile - pink squid - stompable", --"pinksquid",
	"place on a door tile - door - right click for destination sublevel - press up to enter", --"door",
	"place on a wall - ice - makes tile slippery", --"ice",
	"place on empty tile - companion cube", --"box2",
	"place on empty tile - high energy pellet launcher - right", --"energylauncherright",
	"place on empty tile - high energy pellet launcher - left", --"energylauncherleft",
	"place on empty tile - high energy pellet launcher - up", --"energylauncherup",
	"place on empty tile - high energy pellet launcher - down", --"energylauncherdown",
	"place on empty tile - high energy pellet catcher - right - use link", --"energycatcherright",
	"place on empty tile - high energy pellet catcher - left - use link", --"energycatcherleft",
	"place on empty tile - high energy pellet catcher - up - use link", --"energycatcherup",
	"place on empty tile - high energy pellet catcher - down - use link", --"energycatcherdown",
	"place on empty tile - turret - left", --"turretleft",
	"place on empty tile - turret - right", --"turretright",
	"place on empty tile - defective turret - left", --"turret2left",
	"place on empty tile - defective turret - right", --"turret2right",
	"place on empty tile - ! button - push to toggle ! button blocks - right click for colors", --"blocktogglebutton",
	"place on empty tile - ! button block - on - right click for colors", --"buttonblockon",
	"place on empty tile - ! button block - off - right click for colors", --"buttonblockoff",
	"place on empty tile - will produce purple gel to down - purple gel } gravity", --"purplegeldown",
	"place on empty tile - will produce purple gel to right - purple gel } gravity", --"purplegelright",
	"place on empty tile - will produce purple gel to left - purple gel } gravity", --"purplegelleft",
	"place on empty underwater tile - rip van fish - wakes up when player is near", --"sleepfish",
	"place anywhere - turns output on then off - right click to choose delay", --"squarewave",
	"place anywhere - delays an input - right click to choose delay", --"delayer",
	"place anywhere - coin", --"coin",
	"place anywhere - amp - right click to select path", --"amp",
	"place anywhere - green parabeetle - left - goes fast", --"parabeetlegreen",
	"place anywhere - green parabeetle - right - goes fast", --"parabeetlegreenright",
	"place on empty tile - fire appears after a while then dissapears - right click to choose direction", --"longfire",
	"place on tile - cannon ball - right click to choose direction", --"cannonball",
	"place on a wall - mini mushroom", --"minimushroom",
	"place on empty tile - rocket turret - shoots rockets", --"rocketturret",
	"place on empty tile - glados", --"GLaDOS",
	"place on empty tile - portal gun pedestal - right click to choose portals", --"pedestal",
	"place on a wall - portal 1 - right click to choose side - use link tool", --"portal1",
	"place on a wall - portal 2 - right click to choose side - use link tool", --"portal2",
	"place anywhere - text - right click to type text", --"text",
	"place anywhere - region trigger - right click to select region", --"region trigger",
	"place anywhere - tile tool - rightclick to type function", --"tiletool",
	"place on a wall - ice flower", --"iceflower",
	"place on empty tile - shy guy", --"shyguy",
	"place on empty tile - shy guy - more to the right", --"shyguyhalf",
	"place anywhere - enemy tool - rightclick to type enemy to spawn", --"enemytool",
	"place anywhere - randomizer - turns on a random output - right click to choose method", --"randomizer",
	"place on a wall - yoshi egg", --"yoshi",
	"place on empty tile - big ! button - push to toggle ! button blocks - right click for colors",
	"place on empty tile - beetle shell", --"beetleshell",
	"place anywhere - music changer - changes music - right click to select music" --"musicchanger",
}

rightclickvalues = {}
rightclickvalues["platformspawnerup"] = {"width", 1.5, 2, 3, 5}
rightclickvalues["platformspawnerdown"] = {"width", 1.5, 2, 3, 5}
rightclickvalues["platformup"] = {"width", 1.5, 2, 3, 5}
rightclickvalues["platformright"] = {"width", 1.5, 2, 3, 5}
rightclickvalues["platformfall"] = {"width", 1.5, 2, 3, 5}
rightclickvalues["timer"] = {"time", 1, 2, 4, 8}
rightclickvalues["seesaw"] = {"type", 1, 2, 3, 4, 5, 6, 7, 8, 9}

rightclickvalues["pipe"] = {"target", 0, 1, 2, 3, 4, 5, 6}
rightclickvalues["pipespawn"] = {"target", 0, 1, 2, 3, 4, 5, 6}
rightclickvalues["warppipe"] = {"target", 1, 2, 3, 4, 5, 6, 7, 8}
rightclickvalues["vine"] = {"target", 0, 1, 2, 3, 4, 5, 6}

rightclickvalues["castlefirecw"] = {"length", 6, 12}
rightclickvalues["castlefireccw"] = {"length", 6, 12}

rightclickvalues["mazegate"] = {"gateno", 1, 2, 3, 4, 5}

rightclickvalues["geltop"] = {"gelid", 1, 2, 3, 4}
rightclickvalues["gelleft"] = {"gelid", 1, 2, 3, 4}
rightclickvalues["gelbottom"] = {"gelid", 1, 2, 3, 4}
rightclickvalues["gelright"] = {"gelid", 1, 2, 3, 4}

rightclickvalues["icicle"] = {"gravity", 10, 13, 15, 8, 5}

rightclickvalues["kingbill"] = {"speed", 5, 3, 6, 7, 8, 9}

rightclickvalues["pipe2"] = {"target", 0, 1, 2, 3, 4, 5, 6}
rightclickvalues["door"] = {"target", 0, 1, 2, 3, 4, 5, 6}

rightclickvalues["blocktogglebutton"] = {"color", 1, 2, 3, 4}
rightclickvalues["buttonblockon"] = {"color", 1, 2, 3, 4}
rightclickvalues["buttonblockoff"] = {"color", 1, 2, 3, 4}
rightclickvalues["bigblocktogglebutton"] = {"color", 1, 2, 3, 4}

rightclickvalues["delayer"] = {"delay", 1, 2, 3, 4, 5, 6, 7, 8, 9}

rightclickvalues["amp"] = {"path", 1, 2, 3, 4, 0}

rightclickvalues["longfire"] = {"direction", "left", "right", "up", "down"}
rightclickvalues["cannonball"] = {"direction", "left", "right", "down", "up", "left down", "left up", "right down", "right up"}

rightclickvalues["pedestal"] = {"portals", "both", "1 only", "2 only", "gel"}
rightclickvalues["portal1"] = {"side", "left", "right", "up", "down"}
rightclickvalues["portal2"] = {"side", "left", "right", "up", "down"}

rightclickvalues["randomizer"] = {"method", 1, 2}
rightclickvalues["musicchanger"] = {"music", "overworld", "underground", "castle", "underwater", "star", "custom"}

rightclicktype = {}
rightclicktype["text"] = {"text", "text: ", "text|white", "text"}
rightclicktype["regiontrigger"] = {"region trigger", "width height", "1|1", "rt"}
rightclicktype["squarewave"] = {"squarewave", "delay", "0.5", "sq"}
rightclicktype["tiletool"] = {"tiletool", "function", "change to 1", "tt"}
rightclicktype["enemytool"] = {"enemytool", "enemy", "goomba", "et"}

function entity:init(img, x, y, width, height)
	self.image = img
	self.quad = love.graphics.newQuad((x-1)*17, (y-1)*17, 16, 16, width, height)	
end

function entity:sett(i)
	for j = 1, #entitylist do
		if i == j then
			self.t = entitylist[j]
		end
	end
end